apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: doglover
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "uprush/apache-spark/spark:v2.4.5"
  imagePullPolicy: Always
  mainClass: example.DogLover
  mainApplicationFile: "s3a://deephub/user/yijiang/doglover/doglover_2.12-0.1.0-SNAPSHOT.jar"
  sparkVersion: "2.4.5"
  restartPolicy:
    type: Never
  sparkConfigMap: "spark-defaults"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.4
    serviceAccount: spark
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 2.4.4

