apiVersion: v1
kind: Pod
metadata:
  name: spark-client
spec:
  volumes:
    - name: shared-vol
      persistentVolumeClaim:
        claimName: data-client-share
    - name: config-volume
      configMap:
        name: spark-defaults
  containers:
  - name: spark-client
    image: "uprush/apache-spark/spark:2.4.5"
    # Just spin & wait forever
    command: [ "tail", "-f", "/dev/null" ]
    # Configure a mountpoint for the volume we defined above
    volumeMounts:
      - name: shared-vol
        mountPath: /data
      - name: config-volume
        mountPath: /etc/spark/conf
