apiVersion: v1
kind: Pod
metadata:
  name: spark-client
spec:
  sparkConfigMap: "spark-defaults"
  volumes:
    - name: shared-vol
      persistentVolumeClaim:
        claimName: data-client-share
  containers:
  - name: spark-client
    image: "gcr.io/spark-operator/spark:v2.4.5"
    # Just spin & wait forever
    command: [ "tail", "-f", "/dev/null" ]
    # Configure a mountpoint for the volume we defined above
    volumeMounts:
      - name: shared-vol
        mountPath: /data
