apiVersion: v1
kind: Pod
metadata:
  name: hive-client
  namespace: warehouse
spec:
  volumes:
    - name: metastore-cfg-vol
      configMap:
        name: metastore-cfg
  containers:
  - name: hive-client
    image: "uprush/apache-hive:3.1.2"
    imagePullPolicy: Always
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: metastore-s3-keys
          key: access-key
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: metastore-s3-keys
          key: secret-key

    # Just spin & wait forever
    command: [ "tail", "-f", "/dev/null" ]
    # Configure a mountpoint for the volume we defined above
    volumeMounts:
    - name: metastore-cfg-vol
      mountPath: /opt/hive/conf/metastore-site.xml
      subPath: metastore-site.xml
    - name: metastore-cfg-vol
      mountPath: /opt/hadoop/etc/hadoop/core-site.xml
      subPath: core-site.xml
