apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: reddot-postgres
  namespace: default
spec:
  teamId: "reddot"
  volume:
    size: 100Gi
    storageClass: pure-block
  numberOfInstances: 2
  users:
    admin:  # database owner
    - superuser
    - createdb
    hive: []  # role for application hive metastore
  databases:
    metastore: hive  # dbname: owner
  postgresql:
    version: "11"
    